
name: Docker Image Build/Publish tag with commit

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      commit_id:
        description: clone-voice commit id(like 'main' 'dd668d2')
        required: true
        default: main

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    strategy:
      matrix:
        BRANCH_CHECKOUT:
          - ${{ github.event.inputs.commit_id || 'main' }}
        platforms:
          - linux/amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set env git short head
        run: echo "COMMIT_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Meta data image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/clone-voice
            ghcr.io/${{ github.repository_owner }}/clone-voice
          tags: |
            type=raw,value=${{ matrix.BRANCH_CHECKOUT }}
            type=raw,value=${{ env.COMMIT_SHORT }}
          flavor: |
            latest=false

      - name: Build push image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/build@source/dockerfile
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Print image digest
        run: echo ${{ steps.build.outputs.digest }}
